### ISSUE TITLE
Flatbuffers 23.5 change the SO name of the SO that tensorflow links to

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/flatbuffers-feedstock#44]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

```
mamba create --name tf tensorflow=2.11 flatbuffers=23.5 --channel conda-forge --override-channels --yes
mamba activate tf
mamba list flatbuffers
mamba list tensorflow
```

```
python -c "import tensorflow"
```

```
2023-05-27 13:15:11.032245: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/home/mark/mambaforge/envs/tf/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: libflatbuffers.so.23.3.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mark/mambaforge/envs/tf/lib/python3.10/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/mark/mambaforge/envs/tf/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/home/mark/mambaforge/envs/tf/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 77, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "/home/mark/mambaforge/envs/tf/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: libflatbuffers.so.23.3.3: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.
```

Not sure if this is a tensorflow bug or flatbuffers bug. Maybe tensorflow is being too specific in how it links to flatbuffers.
cc: @conda-forge/tensorflow 

### Installed packages

```shell
mark@nuthatch $ mamba list flatbuffers
mamba lis# packages in environment at /home/mark/mambaforge/envs/tf:
#
# Name                    Version                   Build  Channel
flatbuffers               23.5.26              h59595ed_0    conda-forge
python-flatbuffers        23.5.26            pyhd8ed1ab_0    conda-forge
t (tf) ✔ ~
mark@nuthatch $ mamba list tensorflow
# packages in environment at /home/mark/mambaforge/envs/tf:
#
# Name                    Version                   Build  Channel
tensorflow                2.11.1          cuda112py310he87a039_0    conda-forge
tensorflow-base           2.11.1          cuda112py310h4c92a00_0    conda-forge
tensorflow-estimator      2.11.1          cuda112py310h37add04_0    conda-forge
```

### Environment info

```shell
$ conda info

     active environment : tf
    active env location : /home/mark/mambaforge/envs/tf
            shell level : 1
       user config file : /home/mark/.condarc
 populated config files : /home/mark/mambaforge/.condarc
                          /home/mark/.condarc
          conda version : 22.11.1
    conda-build version : 3.24.0
         python version : 3.10.11.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.0=0
                          __glibc=2.35=0
                          __linux=5.19.0=0
                          __unix=0=0
       base environment : /home/mark/mambaforge  (writable)
      conda av data dir : /home/mark/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/mark/mambaforge/pkgs
                          /home/mark/.conda/pkgs
       envs directories : /home/mark/mambaforge/envs
                          /home/mark/.conda/envs
               platform : linux-64
             user-agent : conda/22.11.1 requests/2.29.0 CPython/3.10.11 Linux/5.19.0-41-generic ubuntu/22.04.2 glibc/2.35
                UID:GID : 1003:1003
             netrc file : None
           offline mode : False
```

**Comment by xhochy** [comment]
Given that we have a similar problem with protobuf currently, I would guess it's on the flatbuffers side.

**Comment by hmaarrfk** [comment]
I think it would be good to add a repodata patch pinning stricter for flat buffers and better understand the ABI stability before starting a migration.

I don't have time on my computer today but i can help review things if they come up.

**Comment by hmaarrfk** [comment]
Their so names are "23.3.3" so I presume we need to pin to "x.x.x" instead of "x" unless we do more patching.

**Comment by hmaarrfk** [comment]
```
 $ ls flatbuffers-23.*-hcb278e6_0/lib/
flatbuffers-23.1.21-hcb278e6_0/lib/:
cmake  libflatbuffers.a  libflatbuffers.so  libflatbuffers.so.23.1.21  pkgconfig

flatbuffers-23.1.4-hcb278e6_0/lib/:
cmake  libflatbuffers.a  libflatbuffers.so  libflatbuffers.so.23  libflatbuffers.so.23.1.4  pkgconfig

flatbuffers-23.3.3-hcb278e6_0/lib/:
cmake  libflatbuffers.a  libflatbuffers.so  libflatbuffers.so.23.3.3  pkgconfig

```

it seems that something changed with 23.1.21 and that the "SO" named `.23` was removed.

**Comment by hmaarrfk** [comment]
I found that only 23.3.3 was ever used at conda-forge, so i'm rebuilding a version of flatbuffers as well as the latest.
